---
# tasks file for nightwing
- name: Check OS
  fail:
    msg: "ROLE RUN JUST IN DEBIAN SYSTEM"
  when:
  - ansible_distribution != "Debian"

- name: Remove Graphical Packages
  block:
    - name: Remove Graphical - Include Vars
      include_vars: vars-remove.yml
    - name: Remove Graphical Packages
      apt:
        name: "{{ REMOVE_GRAPHICAL_PACKAGES }}"
        purge: yes 
        state: absent
  tags: remove_gaphical

- name: Package Instalation
  block:
    - name: Install - Include Vars
      include_vars: vars-install.yml
    - name: Install Packages
      include: install_packages.yml 
  tags: install

- name: Package Removal 
  block:
    - name: Remove - Include Vars
      include_vars: vars-remove.yml
    - name: Remove Packages
      include: remove_packages.yml 
  tags: remove

- name: Package Configuration
  block:
    - name: Configuration - Include Vars
      include_vars: vars-configuration.yml
    - name: Configure Packages
      include: configuration_packages.yml 
  tags: configuration

- name: Graphical Configuration
  block:
    - name: Security - Include Vars
      include_vars: vars-graphical.yml
    - name: Security Configuration
      include: graphical_configuration.yml 
  tags: graphical

- name: Security Configuration
  block:
    - name: Security - Include Vars
      include_vars: vars-security.yml
    - name: Security Configuration
      include: security_configuration.yml 
  tags: security
