---
# tasks file for compute
- name: Check OS
  fail:
    msg: "ROLE RUN JUST IN {{ linux_distribution }} SYSTEM"
  when:
  - ansible_distribution != linux_distribution

- name: Package Instalation
  block:
    - name: Install - Include Vars
      include_vars: vars-packages.yml
    - name: Install Packages
      include: install_packages.yml 
  tags: install

- name: Package Removal 
  block:
    - name: Remove - Include Vars
      include_vars: vars-packages.yml
    - name: Remove Packages
      include: remove_packages.yml 
  tags: remove

- name: Package Configuration
  block:
    - name: Configuration - Include Vars
      include_vars: vars-configuration.yml
    - name: Configure Packages
      include: configuration_packages.yml 
  tags: configuration

- name: Security Configuration
  block:
    - name: Security - Include Vars
      include_vars: vars-security.yml
    - name: Security Configuration
      include: security_configuration.yml 
  tags: security
