- name: Remove Packages
  apt:
    name: "{{ REMOVE_PACKAGES }}"
    purge: yes
    state: absent
  when: remove_packages

- name: Remove Unless Dependencies
  apt:
    autoremove: yes
  when: remove_packages

- name: Clean Cache Packages
  apt:
    autoclean: yes
