---
- hosts: all
  remote_user: yago
  become: yes
  become_method: su
  become_flags: "-"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    graphical_environment: gnome
    configure_graphical: true
    remove_current_graphical: false
    configure_compute: true
  roles:
    - { role: graphical, when: "configure_graphical"}
    - { role: compute, when: "configure_compute"}
