---
- hosts: all
  remote_user: "{{ username }}"
  become: yes
  vars:
    username: yago
    graphical_environment: gnome
    configure_graphical: true
    remove_current_graphical: false
    configure_compute: true
  roles:
    - { role: graphical, when: "configure_graphical"}
    - { role: compute, when: "configure_compute"}
