---
# tasks file for nightwing
- name: Check OS
  fail:
    msg: "ROLE RUN JUST IN DEBIAN 10.X SYSTEM"
  when:
  - ansible_os_family != "Debian"
  - ansible_distribuition_major_version is version_compare('10','!=')

- name: Remove Graphical Packages
  block:
    - name: Remove Graphical - Include Vars
      include_vars: vars-remove.yml
    - name: Remove Graphical Packages
      apt:
        name: "{{ REMOVE_GRAPHICAL_PACKAGES }}"
        purge: yes 
        state: absent
  tags: remove_gaphical

- name: Package Instalation
  block:
    - name: Install - Include Vars
      include_vars: vars-install.yml
    - name: Install Packages
      include: install_packages.yml 
  tags: install

- name: Package Removal 
  block:
    - name: Remove - Include Vars
      include_vars: vars-remove.yml
    - name: Remove Packages
      include: remove_packages.yml 
  tags: remove
