---
# tasks file for graphical
- name: Check OS
  fail:
    msg: "ROLE RUN JUST IN {{ linux_distribution }} SYSTEM"
  when:
  - ansible_distribution != linux_distribution

- name: Remove Graphical Packages
  block:
    - name: Remove Graphical Packages
      apt:
        name: "{{ remove_graphical_packages }}"
        purge: yes 
        state: absent
      when: remove_current_graphical
  tags: remove_graphical

- name: Ensure Default "{{ ansible_distribution }}" Repository
  lineinfile:
    path: /etc/apt/sources.list
    regexp: "{{ regexp_repository }}"
    line: "{{ linux_repository }}"
    state: present
  when: ensure_linux_repository

- name: Ensure Dist-Upgrade
  apt:
    update_cache: yes
    upgrade: dist
  when: ensure_linux_repository

- name: Ensure Themes
  block:
    - name: Ensure Themes - tar.gz
      unarchive:
        src: "{{ theme_file }}"
        dest: /usr/share/themes/
    - name: Ensure Themes - apt
      apt:
        name: "{{ themes_packages }}"
        update_cache: yes
        state: present

- name: Graphical Configuration
  block:
    - name: "{{ graphical_environment | upper }} - Include Vars"
      include_vars: "{{ graphical_environment }}.yml"
    - name: Graphical Install and Configuration
      include: "{{ graphical_environment }}_configuration.yml"
      when: enable_graphical_configuration

- name: Ensure GDM3 Started
  systemd:
    name: gdm3
    enabled: yes
    state: started
  when: enable_graphical_configuration
