- name: Install XFCE Minimal
  apt:
    name: "{{ xfce_packages }}"
    state: present
    update_cache: yes
    install_recommends: no

- name: XFCE - Copy Backgroung Image
  copy: 
    src: bg_black.jpg
    dest: /usr/share/images/desktop-base/
      
- name: XFCE - Configure
  block:
    - name: Configure XFCE - directory
      file: 
        path: "/home/{{ username }}/.config/xfce4/"
        owner: "{{ username }}"
        group: "{{ username }}"
        state: directory 
    - name: Configure XFCE - helpers.rc
      lineinfile:
        path: "/home/{{ username }}/.config/xfce4/helpers.rc"
        line: "{{ item }}"
        create: yes
        owner: "{{ username }}"
        group: "{{ username }}"
        state: present
      loop:
      - "WebBrowser={{ webBrowser_default }}"
      - "FileManager={{ fileManager_default }}"  
    - name: Configura XFCE - static files
      synchronize:
        src: "{{ role_path }}/files/xfce4/"
        dest: "/home/{{ username }}/.config/xfce4/"
        perms: yes
        recursive: yes
      become: yes
      become_user: "{{ username }}"
    - name: Configure XFCE - template files
      template:
        src: "{{ item }}"
        dest: "/home/{{ username }}/.config/xfce4/xfconf/xfce-perchannel-xml/"
        owner: "{{ username }}"
        group: "{{ username }}"
      loop:
      - xfce/xfce4-appfinder.xml
      - xfce/xfce4-desktop.xml
      - xfce/xfce4-keyboard-shortcuts.xml
      - xfce/xfce4-panel.xml
      - xfce/xfce4-screensaver.xml
      - xfce/xfce4-settings-editor.xml
      - xfce/xfce4-settings-manager.xml
      - xfce/xfwm4.xml
      - xfce/xsettings.xml

